### ISSUE TITLE
Publish to Spark Packages

### ISSUE THREAD

**Issue by brkyvz** [tizfa/sparkboost#1]
Hi,

Thank you very much for submitting this package to Spark Packages! Would you like to publish the artifacts to the Spark Packages repo as well? This would allow Spark users to easily import your package as easily as:

```
$ $SPARK_HOME/bin/spark-shell --packages tizfa/sparkboost:1.0
```

... instead of building it locally using `mvn install`.

Since your package is a Java package, and you already have a pom, you may use the [spark-package command line tool](https://github.com/databricks/spark-package-cmd-tool) to help your release process. Basically, all you will need to do is first call `mvn package` so that the command line tool can find the binaries in the project directory, and then `spark-package publish` (with the additional flags described in the README).

Please let me know if you have any questions, problems or feedback!

Best,
Burak

**Comment by tizfa** [comment]
Hi Burak, thanks for your suggestion. I am planning to do this thing in the next few days when I will find some spare time. Meanwhile I have improved the code, the documentation coming with the package and released a first stable version of the software (0.5). You can check the details yourself on the updated README.

Tiziano

**Comment by tizfa** [comment]
Done! :-)
